spring.application.name=chat-backend

server.port=8080

spring.data.mongodb.uri=mongodb+srv://root:simun9788@cluster0.8hnfzlh.mongodb.net/chatdb?appName=Cluster0

# logging.level.org.springframework.data.mongodb=DEBUG

# server.servlet.context-path=/api/v1

management.endpoints.web.exposure.include=*

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

cloudflare.r2.endpoint=https://adb770b57e7e1c3be0fa1e1da591bc3f.r2.cloudflarestorage.com
cloudflare.r2.access-key=0aa3cd52f4c035924a946d6e18463d9d
cloudflare.r2.secret-key=3a3ac0433b01ef8f399476fa65d653a5316e901a01cd3a0a37681013ad71c813
r2.bucket.name=chat-app-pc-service
r2.public.url=https://pub-890d071fad034e759ee5b2255c663532.r2.dev

# 32 characters
spring.security.secretKey=ksdubbsUC86532!@#$%^&*1879132krjsdk
